phoneDirectory/emp/routes.py
import os
from flask import current_app, render_template, url_for, flash, redirect, request, Blueprint
from phoneDirectory import db
from phoneDirectory.emp.forms import NewEmployeeForm, EditEmployeeForm
from phoneDirectory.emp.forms import LocationForm, DeleteForm
from phoneDirectory.emp.functions import locOnImage, savePicture
from phoneDirectory.models import Employee
from flask_login import current_user, login_required

emp = Blueprint('emp', __name__)


@emp.route("/addEmployee", methods=['GET', 'POST'])
def addEmployee():
    if not current_user.is_authenticated:
        flash('Login Required.', 'danger')
        return redirect(url_for('main.home'))
    form = NewEmployeeForm()
    if form.cancel.data:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        if form.picture.data:
            picture_fn = savePicture(form.picture.data)
        else:
            picture_fn = "defaultprofile.jpg"
        employee = Employee(firstName=form.firstName.data, lastName=form.lastName.data, extension=form.extension.data,
                            title=form.title.data, department=form.department.data, email=form.email.data,
                            picture=picture_fn, building=form.building.data)
        db.session.add(employee)
        db.session.commit()
        if form.locSelect.data:
            employee = Employee.query.filter_by(email=form.email.data).first()
            return redirect(url_for('emp.empLocation', emp=employee.id))
        else:
            flash(f'Employee"{employee.firstName} {employee.lastName}" created!', 'success')
            return redirect(url_for('main.home'))
    return render_template('addEmployee.html', title='Add Employee', form=form)


@emp.route("/editEmployee", methods=['GET', 'POST'])
def editEmployee():
    if not current_user.is_authenticated:
        flash('Login Required.', 'danger')
        return redirect(url_for('main.home'))
    id = request.args['emp']
    employee = Employee.query.filter_by(id=id).first()
    if not employee:
        flash(f'Error, not a valid employee entry. Please notify site administrator. ID={id}', 'warning')
        return redirect(url_for('main.home'))
    form = EditEmployeeForm(obj=employee)
    if form.cancel.data:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        employee.firstName = form.firstName.data
        employee.lastName = form.lastName.data
        employee.extension = form.extension.data
        employee.title = form.title.data
        employee.department = form.department.data
        employee.email = form.email.data
        employee.building = form.building.data

        if form.resetPicture.data:
            if employee.picture != "defaultprofile.jpg":
                os.remove(os.path.join(current_app.root_path, 'static', 'emp_pictures', employee.picture))
                os.remove(os.path.join(current_app.root_path, 'static', 'emp_pictures', 'full', employee.picture))
            employee.picture = "defaultprofile.jpg"
        elif form.picture.data:
            if not isinstance(form.picture.data, str):
                if employee.picture != "defaultprofile.jpg":
                    os.remove(os.path.join(current_app.root_path, 'static', 'emp_pictures', employee.picture))
                    os.remove(os.path.join(current_app.root_path, 'static', 'emp_pictures', 'full', employee.picture))
                employee.picture = savePicture(form.picture.data)
        if form.resetLocation.data:
            employee.buildingLoc = 'None'
        db.session.commit()

        if form.locSelect.data:
            flash(f'form.locSelect.data = {form.locSelect.data}')
            return redirect(url_for('emp.empLocation', emp=id))
        else:
            flash(f'Employee Record for {employee.firstName} {employee.lastName} updated.',
                  'success')
            return redirect(url_for('main.home'))
    return render_template('editEmployee.html', title='Edit Employee Record', form=form)


@emp.route("/empLocation", methods=['GET', 'POST'])
@login_required
def empLocation():
    args = request.args['emp']
    if "?" in args:
        args = args.split('?')
        id = args[0]
        coords = args[1].split(',')
        xLoc = int(coords[0])
        yLoc = int(coords[1])
        employee = Employee.query.filter_by(id=id).first()
        buildingLoc = locOnImage(employee.building, xLoc, yLoc)
        return redirect(url_for('emp.empLocationConf', emp=id, img=buildingLoc))
    else:
        id = args
    employee = Employee.query.filter_by(id=id).first()
    if not employee:
        flash(f'Employee record error, please notify site administrator. ID={id}', 'danger')
        return redirect(url_for('main.home'))
    return render_template('empLocation.html', title='Add Employee Building Location',
                           emp=id, loc=employee.building)


@emp.route("/empLocationConf", methods=['GET', 'POST'])
@login_required
def empLocationConf():
    id = request.args['emp']
    buildingLoc = request.args['img']

    employee = Employee.query.filter_by(id=id).first()

    form = LocationForm()

    if form.validate_on_submit():
        if form.confirm.data:
            if employee.buildingLoc and employee.buildingLoc != 'None':
                os.remove(os.path.join(current_app.root_path, 'static', 'emp_locations', employee.buildingLoc))
            employee.buildingLoc = buildingLoc
            db.session.commit()
            flash(f'Location saved for {employee.firstName} {employee.lastName}')
            return redirect(url_for('main.home'))
        elif form.redo.data:
            os.remove(os.path.join(current_app.root_path, 'static', 'emp_locations', buildingLoc))
            return redirect(url_for('emp.empLocation', emp=id))
        elif form.cancel.data:
            os.remove(os.path.join(current_app.root_path,'static', 'emp_locations', buildingLoc))
            return redirect(url_for('main.home'))
    # buildingLoc = locOnImage(emp.building, xLoc, yLoc)
    return render_template('empLocationConf.html', title='Confirm Employee Building Location',
                           emp=id, map=buildingLoc, form=form)


@emp.route("/delEmployee", methods=['GET', 'POST'])
@login_required
def delEmployee():
    id = request.args['emp']
    employee = Employee.query.filter_by(id=id).first()
    if not employee:
        flash(f'Employee record error, please notify site administrator. ID={id}', 'danger')
        return redirect(url_for('main.home'))
    form = DeleteForm()
    if form.validate_on_submit():
        if form.confirm.data:
            if employee.buildingLoc and employee.buildingLoc != 'None':
                os.remove(os.path.join(current_app.root_path, 'static', 'emp_locations', employee.buildingLoc))
            if employee.picture != "defaultprofile.jpg":
                os.remove(os.path.join(current_app.root_path, 'static', 'emp_pictures', employee.picture))
                os.remove(os.path.join(current_app.root_path, 'static', 'emp_pictures', 'full', employee.picture))
            db.session.delete(employee)
            db.session.commit()
            flash(f'Employee record deleted.', 'warning')
        elif form.cancel.data:
            flash(f'Record deletion canceled.', 'warning')
        return redirect(url_for('main.home'))

    return render_template('delEmployee.html', title='Delete Employee', first=employee.firstName,
                           last=employee.lastName, form=form)

phoneDirectory/main/routes.py
import os
from flask import render_template, current_app, Blueprint
from phoneDirectory.models import Employee
import json

main = Blueprint('main', __name__)

dataPath = os.path.join(current_app.root_path, 'static', 'data.json')
with open(dataPath) as json_file:
    jsonData = json.load(json_file)
buildingImages = jsonData['BuildingImages']


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', employees=Employee.query.all())


@main.route("/maps")
def maps():
    return render_template('maps.html', buildingImages=buildingImages)

phoneDirectory/templates/about.html
{% extends "layout.html" %}


{% block content %}
	<h1>About</h1>
	<p>v1.0.0, created by Jeff Rice (github jrice128).</p>


{% endblock content %}

phoneDirectory/templates/addAdmin.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ title }}</legend>

				<div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
				</div>			
			</fieldset>
			<div class="form-group"> 
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
			<div class="form-group"> 
				{{ form.cancel(class="btn btn-outline-info") }}
			</div>
		</form>

	</div>
{% endblock content %}

phoneDirectory/templates/addEmployee.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Add Employee</legend>

				<div class="form-group"> 
					{{ form.firstName.label(class="form-control-label") }}

					{% if form.firstName.errors %}
						{{ form.firstName(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.firstName.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.firstName(class="form-control form-control-lg") }}	
					{% endif %}	
				</div>
				<div class="form-group"> 
					{{ form.lastName.label(class="form-control-label") }}
					{% if form.lastName.errors %}
						{{ form.lastName(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.lastName.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.lastName(class="form-control form-control-lg") }}	
					{% endif %}	
				</div>
				<div class="form-group"> 
					{{ form.extension.label(class="form-control-label") }}
					{% if form.extension.errors %}
						{{ form.extension(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.extension.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.extension(class="form-control form-control-lg") }}	
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}	
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.department.label(class="form-control-label") }}
					{% if form.department.errors %}
						{{ form.department(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.department.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.department(class="form-control form-control-lg") }}	
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}	
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.building.label(class="form-control-label") }}
					{% if form.building.errors %}
						{{ form.building(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.building.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.building(class="form-control form-control-lg") }}	
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.picture.label }}
					{{ form.picture(class="form-control-file") }}	
					
					{% if form.picture.errors %}
							{% for error in form.picture.errors %}
								<span class="text-danger">{{ error }}</span></br>
							{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group"> 
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
			<div class="form-group"> 
				{{ form.locSelect(class="btn btn-outline-info") }}
			</div>
			<div class="form-group"> 
				{{ form.cancel(class="btn btn-outline-info") }}
			</div>
		</form>

	</div>
{% endblock content %}

phoneDirectory/templates/admins.html
{% extends "layout.html" %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
	<script type="text/javascript" class="init">
		$(document).ready( function () {
	    	$('#admin_table').DataTable( {
	    		dom: '<"top"lf>rt<"bottom"Bpi><"clear">',
	    		buttons: [
            		'copy', 'csv', 'excel', 'pdf', 'print'
        		]
	    	} );
		} );  
	</script>
{% endblock header %}

{% block content %}

	
	<h3> Current Administrators: </h3>



	<table id="admin_table" class="display">
		<thead>
			<tr>
				<th>Admin Email</th>
				<th>Delete</th>
			</tr>	
		</thead>

		<tbody>
			{% for email in admin %}
				<tr>
					<td>{{ email }}</td>
					<td><a href="{{ url_for('auth.delAdmin', email=email) }}">Delete</a></td>
				</tr>	
			{% endfor %}			
		</tbody>

	</table>



{% endblock content %}

phoneDirectory/templates/delAdmin.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Delete {{ email }}?</legend>
				<div class="form-group"> 
					{{ form.confirm(class="btn btn-outline-info") }}
					</br>
					</br>
					{{ form.cancel(class="btn btn-outline-info") }}
				</div>
			</fieldset>
		</form>
	</div>
{% endblock content %}

phoneDirectory/templates/delEmployee.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Delete {{ first }} {{ last }}?</legend>
				<div class="form-group"> 
					{{ form.confirm(class="btn btn-outline-info") }}
					</br>
					</br>
					{{ form.cancel(class="btn btn-outline-info") }}
				</div>

			</fieldset>

		</form>

	</div>
{% endblock content %}

phoneDirectory/templates/empLocation.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<legend class="border-bottom mb-4">Employee Location</legend>
		<p>Please click on the image to select the Employee's primary location.</p>
		<a href="{{ url_for('emp.empLocation', emp=emp) }}"><img src="{{ url_for('static', filename='building_maps/' + loc + '.png') }}" ismap></a>
		

	</div>
{% endblock content %}

phoneDirectory/templates/empLocationConf.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<legend class="border-bottom mb-4">Employee Location</legend>
		<img src="{{ url_for('static', filename='emp_locations/' + map) }}">
		
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<div class="form-group"> 
				{{ form.confirm(class="btn btn-outline-info") }}
				{{ form.redo(class="btn btn-outline-info") }}
				{{ form.cancel(class="btn btn-outline-info") }}
			</div>
		</form>

	</div>
{% endblock content %}

phoneDirectory/templates/home.html
{% extends "layout.html" %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css">
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
	<script type="text/javascript" class="init">
		$(document).ready( function () {
	    	$('#directory').DataTable( {
			dom: '<"top"lf>rt<"bottom"Bpi><"clear">',
			responsive: true,
			"columnDefs": [
				    { responsivePriority: 1, targets: 0 }
				],
	    		buttons: [
            		'copy', 'csv', 'excel', 'pdf', 'print'
        		]
	    	} );
		} );  
	</script>
{% endblock header %}


{% block content %}

	<h3> Welcome to the employee directory! </h3>
	<p>See below for more info.</p>
	<br>
	<table id="directory" class="display responsive nowrap" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th data-priority="1">First</th>
				<th data-priority="1">Last</th>
				<th data-priority="2">ext.</th>
				<th>Title</th>
				<th>Dept.</th>
				<th data-priority="4">Email</th>
				<th data-priority="3">Photo</th>
				<th data-priority="3">Location</th>
				{% if current_user.is_authenticated %}
				<th>Edit</th>
				<th>Delete</th>
				{% endif %}
			</tr>	
		</thead>

		<tbody>
			{% for emp in employees %}
				<tr>
					<td>{{ emp.firstName }}</td>
					<td>{{ emp.lastName }}</td>
					<td>{{ emp.extension }}</td>
					<td>{{ emp.title }}</td>
					<td>{{ emp.department }}</td>
					<td><a href="{{ 'mailto:' + emp.email }}">{{ emp.email }}</a></td>
					<td><a href="{{url_for('static', filename='emp_pictures/full/' + emp.picture)}}" target="_blank"><img src="{{url_for('static', filename='emp_pictures/' + emp.picture)}}"></a></td>

					{% if emp.buildingLoc == 'None' %}
						<td>{{ emp.building }}</td>
					{% else %}
						<td><a href="{{url_for('static', filename='emp_locations/' + emp.buildingLoc)}}" target="_blank">{{ emp.building }}</a></td>
					{% endif %}

					{% if current_user.is_authenticated %}
					<td><a href="{{ url_for('emp.editEmployee', emp=emp.id) }}">Edit</a></td>
					<td><a href="{{ url_for('emp.delEmployee', emp=emp.id) }}">Delete</a></td>
					{% endif %}
				</tr>	
			{% endfor %}			
		</tbody>
	</table>
	<br>
	<h3>How to:</h3>
	<li>
		Use the search bar to dynamically filter the directory based on any column.
	</li>
	<li>
		Use the buttons below the table to save/print the full directory in your selected order.  Search first to save/print a subset.
	</li>
	<li>
		If an employee's location is blue, click the location to see their desk location in the building (marked with a green dot).
	</li>
	<li>
		Click on an employee's photo to see the full-size photo.
	</li>
	<li>
		Not familiar with a building's layout?  Click 'Maps' at the top of the page!
	</li>
	</br>
	</br>
	
{% endblock content %}

phoneDirectory/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	{% if title %}
		<title>Employee Directory - {{ title }}</title>
	{% else %}
		<title>Employee Directory</title>
	{% endif %}
	<meta charset="utf-8">
	<script src="{{ url_for('static', filename='jquery.js')}}"></script>
	
	{% block header %}{% endblock header %}

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-green fixed-top">
	    <div class="container">
	      <a class="navbar-brand" href="#">
    		<img src="{{ url_for('static', filename="headerlogo.png") }}" width="25" height="25" alt="">
  		  </a>
	      <a class="navbar-brand mr-4" href="/">Employee Directory</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
	          <a class="nav-item nav-link" href="{{ url_for('main.maps') }}">Maps</a>
	          {% if current_user.is_authenticated %}
	          	<a class="nav-item nav-link" href="{{ url_for('emp.addEmployee') }}">Add Employee</a>
	          	<a class="nav-item nav-link" href="{{ url_for('auth.admins') }}">Admin List</a>
	          	<a class="nav-item nav-link" href="{{ url_for('auth.addAdmin') }}">Add Admin</a>
	          {% endif %}
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	           	{% if current_user.is_authenticated %}
	        	<a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
	        	{% else %}
	           		<a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Admin</a>
	           	{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md">
	    	{% with messages = get_flashed_messages(with_categories=true) %}
	    	{% if messages %}
	    		{% for category, message in messages %}
	    			<div class="alert alert-{{ category }}">
	    				{{ message }}
	    				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    					<span aria-hidden="true">&times;</span>
	    				</button>
	    			</div>
	    		{% endfor %}
	    	{% endif %}

	    	{% endwith %}

	      {% block content %}{% endblock content %}
	    	
	    </div>

	  </div>
	</main>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<footer class="footer">
		<div class="container">
			<div class="small-font">
				Written and designed in Python with Flask by <a class="email-link" href="mailto:jrice@jeffdrice.com"> Jeff Rice</a>.
				<a class="email-link right" href="mailto:{{ config.ADMIN_EMAIL }}?subject=DirectoryHelp">Contact Admin</a>
			</div>
		</div>
	</footer>
</body>
</html>

phoneDirectory/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Admin Login</legend>

				<div class="form-group"> 
					{{ form.email.label(class="form-control-label") }}
					{{ form.email(class="form-control form-control-lg") }}
				</div>
				<div class="form-group"> 
					{{ form.password.label(class="form-control-label") }}
					{{ form.password(class="form-control form-control-lg") }}
				</div>
				<div class="form-check"> 
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group"> 
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>

	</div>
{% endblock content %}

phoneDirectory/templates/maps.html
{% extends "layout.html" %}


{% block content %}
	<h1>Building Maps</h1>
	</br>
	</br>
	</br>
	{% for building in buildingImages %}
		<span class="form-group"> 
			<a class="btn btn-outline-info" href="{{ url_for('static', filename='building_maps/' + buildingImages[building]) }}">{{ building }}</a>
		</span>
	{% endfor %}


{% endblock content %}